### ISSUE TITLE
how to listen Drag Gshape like `MouseMove` ?

### ISSUE THREAD

**Issue by imiskolee** [roipeker/graphx#25]
hi:
how  to listen dragging position like mousemove event ?

**Comment by imiskolee** [comment]
I just handle the `MouseMove` event now, but it's not working when I drag fast.

**Comment by roipeker** [comment]
You have the startDrag/stopdrag methods
Usually i listen to stage.onMouseMove if i have to track position, otherwise, you can also use stage.onEnterFrame.add() and track with the ticker mouseX and mouseY.

Maybe you are trying to capture an event on some displayobject that has other children, and there is a bug... try to use mouseChildren=false to prevent signal propagations down the display list

**Comment by imiskolee** [comment]
thanks.
